import type { LucideIcon } from "lucide-react";
import {
  BadgePercent,
  BarChart3,
  Building2,
  CalendarDays,
  ClipboardList,
  Clock,
  CreditCard,
  Gift,
  Home,
  IndianRupee,
  LayoutGrid,
  LifeBuoy,
  ListChecks,
  Megaphone,
  Package,
  Receipt,
  Scissors,
  Search,
  Settings,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Truck,
  UserRound,
  Users,
  Wallet,
  Warehouse,
  CalendarOff,
  Armchair,
  TrendingUp,
} from "lucide-react";
import type { Role } from "@/lib/types";

export interface NavItem {
  label: string;
  href: string;
  icon: LucideIcon;
  /** Shown in mobile bottom nav (max 5 per role) */
  primary?: boolean;
  section?: string;
}

export const NAV: Record<Role, NavItem[]> = {
  customer: [
    { label: "Home", href: "/customer", icon: Home, primary: true },
    { label: "Explore", href: "/customer/explore", icon: Search, primary: true },
    { label: "Bookings", href: "/customer/bookings", icon: CalendarDays, primary: true },
    { label: "Rewards", href: "/customer/loyalty", icon: Gift, primary: true },
    { label: "Profile", href: "/customer/profile", icon: UserRound, primary: true },
    { label: "Memberships", href: "/customer/memberships", icon: Sparkles },
    { label: "Wallet", href: "/customer/wallet", icon: Wallet },
    { label: "Offers", href: "/customer/offers", icon: BadgePercent },
    { label: "Favorites", href: "/customer/favorites", icon: Star },
    { label: "My Reviews", href: "/customer/reviews", icon: Star },
  ],
  barber: [
    { label: "Today", href: "/staff", icon: Home, primary: true },
    { label: "Queue", href: "/staff/queue", icon: ListChecks, primary: true },
    { label: "Schedule", href: "/staff/schedule", icon: CalendarDays, primary: true },
    { label: "Customers", href: "/staff/customers", icon: Users, primary: true },
    { label: "Earnings", href: "/staff/earnings", icon: IndianRupee, primary: true },
    { label: "Commissions", href: "/staff/commissions", icon: Receipt },
    { label: "Leave", href: "/staff/leave", icon: CalendarOff },
    { label: "Profile", href: "/staff/profile", icon: UserRound },
  ],
  receptionist: [
    { label: "Today", href: "/reception", icon: Home, primary: true },
    { label: "Queue", href: "/reception/queue", icon: ListChecks, primary: true },
    { label: "Calendar", href: "/reception/calendar", icon: CalendarDays, primary: true },
    { label: "POS", href: "/reception/pos", icon: CreditCard, primary: true },
    { label: "Check-in", href: "/reception/check-in", icon: ClipboardList },
    { label: "Customers", href: "/reception/customers", icon: Users },
    { label: "Payments", href: "/reception/payments", icon: Receipt },
    { label: "Closing", href: "/reception/closing", icon: Wallet },
  ],
  manager: [
    { label: "Overview", href: "/manager", icon: Home, primary: true },
    { label: "Calendar", href: "/manager/calendar", icon: CalendarDays, primary: true },
    { label: "Staff", href: "/manager/staff", icon: Users, primary: true },
    { label: "Leave", href: "/manager/leave", icon: CalendarOff, primary: true },
    { label: "Shifts", href: "/manager/shifts", icon: Clock },
    { label: "Performance", href: "/manager/performance", icon: TrendingUp },
    { label: "Inventory", href: "/manager/inventory", icon: Package },
    { label: "Reports", href: "/manager/reports", icon: BarChart3 },
  ],
  owner: [
    { label: "Home", href: "/owner", icon: Home, primary: true, section: "Overview" },
    { label: "Calendar", href: "/owner/calendar", icon: CalendarDays, primary: true, section: "Operations" },
    { label: "Customers", href: "/owner/customers", icon: Users, primary: true, section: "People" },
    { label: "Insights", href: "/owner/analytics", icon: BarChart3, primary: true, section: "Intelligence" },
    { label: "Queue", href: "/owner/queue", icon: ListChecks, section: "Operations" },
    { label: "Staff", href: "/owner/staff", icon: Scissors, section: "People" },
    { label: "Services", href: "/owner/services", icon: LayoutGrid, section: "Catalog" },
    { label: "Resources", href: "/owner/resources", icon: Armchair, section: "Catalog" },
    { label: "Inventory", href: "/owner/inventory", icon: Package, section: "Supply" },
    { label: "Vendors", href: "/owner/vendors", icon: Truck, section: "Supply" },
    { label: "Purchase Orders", href: "/owner/purchase-orders", icon: ShoppingCart, section: "Supply" },
    { label: "Expenses", href: "/owner/expenses", icon: Receipt, section: "Finance" },
    { label: "Payroll", href: "/owner/payroll", icon: IndianRupee, section: "Finance" },
    { label: "Memberships", href: "/owner/memberships", icon: Sparkles, section: "Growth" },
    { label: "Loyalty", href: "/owner/loyalty", icon: Gift, section: "Growth" },
    { label: "Offers", href: "/owner/offers", icon: BadgePercent, section: "Growth" },
    { label: "Marketing", href: "/owner/marketing", icon: Megaphone, section: "Growth" },
    { label: "Reviews", href: "/owner/reviews", icon: Star, section: "Growth" },
    { label: "Reports", href: "/owner/reports", icon: ClipboardList, section: "Intelligence" },
    { label: "Branches", href: "/owner/branches", icon: Building2, section: "Organization" },
    { label: "Settings", href: "/owner/settings", icon: Settings, section: "Organization" },
    { label: "Billing", href: "/owner/billing", icon: CreditCard, section: "Organization" },
    { label: "Integrations", href: "/owner/integrations", icon: Warehouse, section: "Organization" },
  ],
  admin: [
    { label: "Overview", href: "/admin", icon: Home, primary: true },
    { label: "Shops", href: "/admin/shops", icon: Store, primary: true },
    { label: "Subscriptions", href: "/admin/subscriptions", icon: CreditCard, primary: true },
    { label: "Support", href: "/admin/support", icon: LifeBuoy, primary: true },
    { label: "Users", href: "/admin/users", icon: Users },
    { label: "Payments", href: "/admin/payments", icon: IndianRupee },
    { label: "Reviews", href: "/admin/reviews", icon: Star },
    { label: "Analytics", href: "/admin/analytics", icon: BarChart3 },
    { label: "Settings", href: "/admin/settings", icon: Settings },
  ],
};
